export const STORE_ITEMS = 'STORE_ITEMS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const SUB_QUANTITY = 'SUB_QUANTITY'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const IS_LOGIN = 'IS_LOGIN'
export const LOGOUT = 'LOGOUT'
export const CLEARCART = 'CLEARCART'
